ALL_LOCATIONS: tuple[str, ...] = (
    "Aviano",
    "Babno Polje",
    "Beljak",
    "Benetke",
    "Bihač",
    "Bilje pri Novi Gorici",
    "Bled",
    "Blegoš",
    "Bohinjska Češnjica",
    "Boršt Gorenja vas",
    "Bovec",
    "Breginj",
    "Brežice",
    "Bukovski vrh",
    "Celje",
    "Celovec",
    "Cerknica",
    "Cerkniško jezero",
    "Davča",
    "Dolenje pri Ajdovščini",
    "Domžale",
    "Gačnik",
    "Godnje",
    "Gornji Grad",
    "Gradec",
    "Gradež",
    "Grosuplje",
    "Hočko Pohorje",
    "Hrastnik",
    "Idrija",
    "Ilirska Bistrica",
    "Iskrba",
    "Izola",
    "Jelendol",
    "Jeronim",
    "Jeruzalem",
    "Jesenice",
    "Jezersko",
    "Juršče",
    "Kadrenci",
    "Kamnik",
    "Kamniška Bistrica",
    "Kanin",
    "Karlovec",
    "Kneške Ravne",
    "Koper",
    "Koper Markovec",
    "Korensko sedlo",
    "Korošče",
    "Kočevje",
    "Kočevske Poljane",
    "Krajinski park Goričko",
    "Kranj",
    "Krapina",
    "Kredarica",
    "Krk",
    "Krn",
    "Krvavec",
    "Krško",
    "Kubed",
    "Kum",
    "Lendava",
    "Letališče Cerklje ob Krki",
    "Letališče Edvarda Rusjana Maribor",
    "Letališče Jožeta Pučnika Ljubljana",
    "Letališče Lesce",
    "Letališče Portorož",
    "Lienz",
    "Lisca",
    "Litija",
    "Ljubljana",
    "Ljubljana - Vič",
    "Ljubno ob Savinji",
    "Logarska dolina",
    "Logatec",
    "Lucija",
    "Luka Koper",
    "Luče",
    "Malkovec",
    "Maribor",
    "Marinča vas",
    "Mačkovci",
    "Medvode",
    "Mengeš",
    "Metlika",
    "Mežica",
    "Miklavž na Dravskem polju",
    "Miklavž na Gorjancih",
    "Murska Sobota",
    "Nanos",
    "Nova Gorica",
    "Nova vas - Bloke",
    "Novo mesto",
    "Ogulin",
    "Osilnica",
    "Otlica",
    "Park Škocjanske jame",
    "Pasja ravan",
    "Pavličevo sedlo",
    "Pazin",
    "Piran",
    "Planica",
    "Planina pod Golico",
    "Planina v Podbočju",
    "Podnanos",
    "Podčetrtek",
    "Postojna",
    "Predel",
    "Prevalje",
    "Ptuj",
    "Pulj",
    "Rab",
    "Radegunda",
    "Radenci",
    "Radovljica",
    "Rateče",
    "Ratitovec",
    "Ravne na Koroškem",
    "Reka",
    "Ribnica - Dolenji Lazi",
    "Rogaška Slatina",
    "Rogla",
    "Rovinj",
    "Rudno polje",
    "Ruše",
    "Senj",
    "Sevnica",
    "Sevno",
    "Sežana",
    "Sisak",
    "Slavnik",
    "Slovenska Bistrica",
    "Slovenske Konjice",
    "Sviščaki",
    "Tablja",
    "Tatre",
    "Tolmeč",
    "Tolmin - Volče",
    "Topol",
    "Trbovlje",
    "Trebnje",
    "Trije Kralji na Pohorju",
    "Trojane - Limovce",
    "Trst",
    "Trzin",
    "Uršlja gora",
    "Varaždin",
    "Vedrijan",
    "Velenje",
    "Velike Lašče",
    "Videm",
    "Vogel",
    "Volšperk",
    "Vransko",
    "Vrhnika",
    "Vršič",
    "Zadlog",
    "Zagorje",
    "Zagreb",
    "Zalaegerszeg",
    "Zavodnje",
    "Zelenica",
    "Zgornja Kapla",
    "Zgornja Radovna",
    "Zgornja Sorica",
    "Črnomelj",
    "Šebreljski vrh",
    "Šentjur",
    "Škofja Loka",
    "Šmarje pri Jelšah",
    "Šmartno pri Slovenj Gradcu",
    "Špital",
    "Žalec",
    "Žiri",
)

OBSERVATION_STATIONS = {
    "Babno Polje": "1401",
    "Bilje pri Novi Gorici": "1402",
    "Blegoš": "1403",
    "Bohinjska Češnjica": "1404",
    "Boršt Gorenja vas": "1496",
    "Bovec": "1030",
    "Breginj": "1405",
    "Bukovski vrh": "1406",
    "Celje": "1025",
    "Cerkniško jezero": "1407",
    "Davča": "1409",
    "Dolenje pri Ajdovščini": "2002",
    "Gačnik": "1411",
    "Godnje": "1412",
    "Gornji Grad": "1414",
    "Hočko Pohorje": "1415",
    "Hrastnik": "3414",
    "Idrija": "1416",
    "Ilirska Bistrica": "1037",
    "Iskrba": "1417",
    "Jeronim": "1419",
    "Jeruzalem": "1420",
    "Jezersko": "1489",
    "Kamniška Bistrica": "1423",
    "Kanin": "1424",
    "Koper": "1038",
    "Koper Markovec": "3423",
    "Korensko sedlo": "1428",
    "Kočevje": "1426",
    "Krajinski park Goričko": "1027",
    "Kranj": "1429",
    "Kredarica": "1430",
    "Krn": "1431",
    "Krvavec": "1432",
    "Krško": "3098",
    "Kubed": "1433",
    "Kum": "1434",
    "Lendava": "1028",
    "Letališče Cerklje ob Krki": "1035",
    "Letališče Edvarda Rusjana Maribor": "1492",
    "Letališče Jožeta Pučnika Ljubljana": "1493",
    "Letališče Lesce": "1034",
    "Letališče Portorož": "1008",
    "Lisca": "1435",
    "Litija": "1436",
    "Ljubljana": "1495",
    "Ljubljana - Vič": "3404",
    "Logarska dolina": "1437",
    "Logatec": "1438",
    "Luka Koper": "2001",
    "Malkovec": "1029",
    "Maribor": "1491",
    "Marinča vas": "1410",
    "Metlika": "1441",
    "Mežica": "1442",
    "Miklavž na Gorjancih": "1443",
    "Murska Sobota": "1444",
    "Nanos": "1445",
    "Nova Gorica": "3421",
    "Nova vas - Bloke": "1446",
    "Novo mesto": "1447",
    "Osilnica": "1448",
    "Otlica": "3424",
    "Park Škocjanske jame": "3029",
    "Pasja ravan": "1449",
    "Pavličevo sedlo": "1450",
    "Planina pod Golico": "1451",
    "Podnanos": "1454",
    "Podčetrtek": "1019",
    "Postojna": "1455",
    "Predel": "1456",
    "Ptuj": "1457",
    "Radegunda": "1413",
    "Rateče": "1031",
    "Ratitovec": "1458",
    "Ravne na Koroškem": "1026",
    "Rogaška Slatina": "1461",
    "Rogla": "1462",
    "Rudno polje": "1463",
    "Sevno": "1465",
    "Slavnik": "1466",
    "Slovenske Konjice": "1467",
    "Sviščaki": "1470",
    "Tatre": "1472",
    "Tolmin - Volče": "1473",
    "Topol": "1474",
    "Trbovlje": "3413",
    "Trebnje": "1475",
    "Trije Kralji na Pohorju": "1468",
    "Trojane - Limovce": "1476",
    "Uršlja gora": "1477",
    "Vedrijan": "1478",
    "Velenje": "1479",
    "Velike Lašče": "1480",
    "Vogel": "1481",
    "Vrhnika": "1483",
    "Vršič": "1484",
    "Zadlog": "1408",
    "Zelenica": "1486",
    "Zgornja Kapla": "1459",
    "Zgornja Radovna": "1487",
    "Zgornja Sorica": "1488",
    "Črnomelj": "1033",
    "Šebreljski vrh": "1482",
    "Šmartno pri Slovenj Gradcu": "1471",
}
