"""Static mapping of ARSO weather stations that have webcams.

Each key is a station display name (matching ``station_map.OBSERVATION_STATIONS``),
and the value is a list of available compass directions.

Generated by probing the ARSO webcam JSON API:
``webcam_METEO-{station_id}_{direction}_data.json``

Last updated: 2026-03-13
"""

WEBCAM_STATIONS: dict[str, list[str]] = {
    "Bilje pri Novi Gorici": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Blegoš": ["ne", "se", "s"],
    "Bovec": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Celje": ["n", "w"],
    "Cerkniško jezero": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Dolenje pri Ajdovščini": ["nw"],
    "Hočko Pohorje": ["n", "e"],
    "Jeruzalem": ["se", "sw", "w"],
    "Kanin": ["e", "sw", "nw"],
    "Koper": ["n", "e"],
    "Koper Markovec": ["n", "e"],
    "Korensko sedlo": ["s", "nw"],
    "Kredarica": ["e", "se", "sw", "w"],
    "Krn": ["n", "e", "se"],
    "Krvavec": ["s", "w"],
    "Kum": ["e", "s", "nw"],
    "Letališče Edvarda Rusjana Maribor": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Letališče Jožeta Pučnika Ljubljana": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Letališče Portorož": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Lisca": ["n", "e", "s", "w"],
    "Ljubljana": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Logarska dolina": ["n", "sw"],
    "Maribor": ["ne", "sw"],
    "Miklavž na Gorjancih": ["e", "sw"],
    "Murska Sobota": ["sw", "nw"],
    "Nanos": ["se", "sw"],
    "Novo mesto": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Otlica": ["s"],
    "Pasja ravan": ["n", "e", "s", "w"],
    "Pavličevo sedlo": ["ne", "w"],
    "Postojna": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Predel": ["e", "w"],
    "Ptuj": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Radegunda": ["se", "sw", "w"],
    "Ratitovec": ["se", "sw", "nw"],
    "Rogla": ["sw", "nw"],
    "Rudno polje": ["ne", "s"],
    "Slavnik": ["n", "sw"],
    "Sviščaki": ["ne"],
    "Tolmin - Volče": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Trije Kralji na Pohorju": ["ne", "nw"],
    "Trojane - Limovce": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Uršlja gora": ["se", "sw", "nw"],
    "Vogel": ["n", "e", "w"],
    "Vrhnika": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
    "Vršič": ["ne", "sw"],
    "Zelenica": ["se", "w"],
    "Zgornja Kapla": ["e", "sw"],
    "Zgornja Sorica": ["se", "sw"],
    "Šebreljski vrh": ["ne", "s"],
    "Šmartno pri Slovenj Gradcu": ["n", "ne", "e", "se", "s", "sw", "w", "nw"],
}
